version: "3.8"

services:
  redis:
    image: redis:5.0.1
    container_name: redis
    restart: always
    volumes:
      - ./redis_volume_data:/data
    ports:
      - 6379:6379
    networks:
      - my_networks
  db:
    container_name: task_postgresql_db
    image: postgres:alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - my_networks
  app:
    container_name: task-app
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8009 --reload"
    volumes:
      - .:/app
    ports:
      - 8009:8009
    depends_on:
      - db
      - redis
    restart: always
    networks:
      - my_networks
networks:
    my_networks: